import { defineGuide } from '../../lib/guide-types';
import { P } from '../../lib/engine/params';

// Valeurs lues dans params-2026.json, bloc `transport_personnes` : code des transports, articles R3113-35 à
// R3113-42 (capacité professionnelle) et L3112-1 ; lus sur Légifrance le 4 octobre 2026.
const X = P.transport_personnes;

export default defineGuide({
  id: 'capacite-transport-personnes',
  group: 'autres',
  order: 80,
  mini: 'voieCapacite',
  miniHref: 'licence-transport',
  related: ['licence-transport', 'devenir-chauffeur-bus', 'devenir-chauffeur-vtc', 'registre-vtc', 'statut-vtc'],
  sources: ['ctR3113CapPro', 'ctL3113', 'ctL3112_1', 'ctL3120', 'arreteJuryCapacite'],
  fr: {
    slug: 'capacite-transport-personnes',
    nav: 'Capacité de transport de personnes',
    card: 'L’attestation du gestionnaire de transport : examen, diplômes, expérience, et ce qu’elle permet.',
    title: 'Capacité de transport de personnes 2026 : examen et voies',
    description: `Capacité de transport de personnes en 2026 : attestation complète ou limitée à ${X.leger_places_conducteur_inclus} places, examen écrit, diplômes, ${X.cappro_experience_leger_ans} ans de gestion, articles R3113-35 à R3113-42.`,
    h1: 'Capacité de transport de personnes : l’attestation, l’examen, les dispenses',
    intro: 'Sans cette attestation au nom d’un gestionnaire, aucune entreprise de transport public de personnes n’entre au registre.',
    resume: `La capacité de transport de personnes est l’attestation de capacité professionnelle exigée du gestionnaire de transport pour inscrire une entreprise de transport public routier de personnes au registre tenu par l’État (code des transports, articles L3113-1 et R3113-38). Elle existe en deux versions, délivrées par le préfet de région. L’attestation complète, valable pour tous les véhicules dont les autocars, s’obtient par un examen écrit portant sur les matières de l’annexe I du règlement (CE) n° 1071/2009 (article R3113-35) ou par un diplôme qui les couvre toutes. L’attestation limitée aux véhicules de ${X.leger_places_conducteur_inclus} places au plus, conducteur compris, demande une formation dans un centre agréé puis un examen écrit (article R3113-39), ou ${X.cappro_experience_leger_ans} ans de gestion continue d’une entreprise de transport de personnes, interrompue depuis moins de ${X.cappro_interruption_max_ans} ans (article R3113-40). Le chauffeur de taxi ou de VTC n’en a pas besoin : son activité relève d’un autre titre du code, avec sa carte professionnelle.`,
    faqs: [
      { q: 'Un chauffeur VTC a-t-il besoin de la capacité de transport ?', a: 'Non. L’article L3120-1 du code des transports place les prestations payantes avec des véhicules de moins de dix places, taxis et VTC, dans un titre à part, qui exclut les transports publics collectifs. Le VTC passe l’examen de la chambre de métiers, obtient sa carte professionnelle et inscrit son entreprise au registre des VTC. La capacité de transport concerne les entreprises de transport collectif.' },
      { q: 'Qu’appelle-t-on la capacité LOTI ?', a: `C’est le nom courant de l’attestation de capacité professionnelle limitée aux véhicules de ${X.leger_places_conducteur_inclus} places au plus, conducteur compris. LOTI renvoie à la loi d’orientation des transports intérieurs de 1982, dont les règles sont aujourd’hui reprises dans le code des transports. L’attestation est délivrée par le préfet de région après une formation et un examen écrit, ou sur diplôme, ou après ${X.cappro_experience_leger_ans} ans de gestion d’une entreprise du secteur (articles R3113-39 et R3113-40).` },
      { q: 'Peut-on obtenir la capacité de transport sans passer l’examen ?', a: `Oui, dans deux cas. Un diplôme figurant sur la liste fixée par arrêté, qui couvre toutes les matières exigées, permet d’obtenir l’attestation (articles R3113-36 et R3113-40). Pour l’attestation limitée aux petits véhicules, ${X.cappro_experience_leger_ans} années de gestion continue et principale d’une entreprise de transport public de personnes suffisent, si l’activité n’a pas cessé depuis plus de ${X.cappro_interruption_max_ans} ans.` },
      { q: 'La capacité de transport de personnes expire-t-elle ?', a: `L’attestation n’a pas de date de fin dans les articles R3113-35 à R3113-42. En revanche, une personne qui n’a pas géré d’entreprise de transport public de personnes dans les ${X.cappro_actualisation_inactivite_ans} années précédant sa demande peut être obligée par le préfet de région de suivre une formation d’actualisation des connaissances avant d’être désignée gestionnaire de transport (article R3113-41).` },
      { q: 'Une attestation obtenue dans un autre pays de l’Union est-elle reconnue ?', a: 'Oui. L’article R3113-37 du code des transports reconnaît comme preuve suffisante de capacité professionnelle les attestations délivrées par les autorités compétentes des autres États membres de l’Union européenne, selon le modèle du règlement (CE) n° 1071/2009. Les attestations délivrées avant le 4 décembre 2011 sont réputées équivalentes (article R3113-42).' },
      { q: 'Avec une capacité limitée aux petits véhicules, peut-on faire du transport occasionnel en ville ?', a: `Pas partout. Selon l’article L3112-1 du code des transports, un service occasionnel dont le départ et l’arrivée sont dans le ressort d’une même autorité organisatrice tenue d’établir un plan de mobilité doit être exécuté avec un véhicule comportant plus de ${X.places_passagers_max_m1} places assises en plus du conducteur. Les véhicules légers y sont donc exclus.` },
    ],
    body: (h) => `
<h2>À quoi sert l’attestation</h2>
<p>Toute entreprise de transport public de personnes établie en France doit être inscrite à un registre tenu par l’État, et l’inscription peut être subordonnée à des conditions d’établissement, d’honorabilité professionnelle, de capacité financière et de capacité professionnelle (${h.src('ctL3113', 'article L3113-1 du code des transports')}). La capacité professionnelle n’est pas demandée à l’entreprise en bloc : elle est portée par une personne, le gestionnaire de transport, qui doit détenir l’attestation (article R3113-38). Dans une petite structure, c’est souvent le dirigeant lui-même.</p>
<p>L’attestation ne donne pas le droit de conduire : c’est un titre de gestion. Le conducteur d’un car a besoin du permis D et de la qualification initiale, détaillés dans la page ${h.a('devenir-chauffeur-bus', 'devenir chauffeur de bus')}. Une même personne peut cumuler les deux rôles.</p>

<h2>Qui en a besoin, et qui n’en a pas besoin</h2>
<p>L’attestation concerne les transports publics collectifs : lignes régulières, transport scolaire, services occasionnels comme les excursions, les navettes d’événements ou les transferts de groupes, transport à la demande. L’entreprise vend un transport de personnes, à titre onéreux.</p>
<p>Deux familles en sont dispensées par la structure même du code. Les taxis et les VTC relèvent d’un titre propre, qui s’applique aux prestations payantes avec des véhicules de moins de dix places, à l’exclusion des transports publics collectifs (${h.src('ctL3120', 'article L3120-1')}) : leur sésame est la carte professionnelle, après l’examen de la chambre de métiers, puis, pour le VTC, le ${h.a('registre-vtc', 'registre des VTC')}. Les services privés, ensuite : une entreprise ou une association qui transporte son propre personnel ou ses membres pour ses besoins normaux de fonctionnement n’exerce pas une activité de transport public (${h.src('ctL3131', 'article L3131-1')}).</p>

<h2>Deux attestations, deux périmètres</h2>
${h.table(['', 'Attestation complète', `Attestation limitée à ${X.leger_places_conducteur_inclus} places`], [
  ['Véhicules couverts', 'tous, dont autocars et autobus', `${X.leger_places_conducteur_inclus} places au plus, conducteur compris`],
  ['Voie de l’examen', 'examen écrit sur l’annexe I du règlement (CE) n° 1071/2009 (R3113-35)', 'formation dans un centre agréé, puis examen écrit sur un référentiel ministériel (R3113-39)'],
  ['Voie du diplôme', 'diplôme couvrant toutes les matières de l’annexe I (R3113-36, 1°)', 'diplôme couvrant le référentiel, parfois avec l’examen écrit (R3113-40, 1°)'],
  ['Voie de l’expérience', `gestion continue pendant les ${X.cappro_experience_lourd_ans} ans précédant le 4 décembre 2009 (R3113-36, 2°)`, `${X.cappro_experience_leger_ans} ans de gestion continue et principale, arrêt depuis moins de ${X.cappro_interruption_max_ans} ans (R3113-40, 2°)`],
], 'Source : code des transports, articles R3113-35 à R3113-40, lus sur Légifrance le 4 octobre 2026')}
<p>Le choix dépend de la flotte visée, pas de la taille de l’entreprise. Une société qui exploite un seul minibus de plus de neuf places, conducteur compris, a besoin de l’attestation complète. Une entreprise de dix monospaces de huit places passagers peut se contenter de l’attestation limitée.</p>

<h2>L’examen de l’attestation complète</h2>
<p>L’${h.src('ctR3113CapPro', 'article R3113-35')} prévoit un examen écrit obligatoire sur les matières énumérées à l’annexe I du règlement européen de 2009 qui encadre la profession de transporteur par route. Ce programme couvre le droit civil, commercial, social et fiscal, la gestion commerciale et financière de l’entreprise, l’accès au marché, les normes techniques, la sécurité routière. L’organisation de l’examen est financée par une redevance pour service rendu, limitée à un seul passage. Le jury, national, réunit des représentants de l’administration, des organisations professionnelles et des organismes de formation ; sa composition est fixée par l’${h.src('arreteJuryCapacite', 'arrêté du 2 septembre 2025')}.</p>
<p>Les articles lus ne fixent ni le montant de la redevance, ni le calendrier des sessions, ni la note de réussite : ces éléments sont publiés à part par l’administration chaque année. Nous ne les reprenons pas tant que nous ne les avons pas lus sur une source officielle datée.</p>

<h2>L’attestation limitée aux véhicules légers</h2>
<p>L’article R3113-39 vise les entreprises qui utilisent exclusivement des véhicules de ${X.leger_places_conducteur_inclus} places au plus, conducteur compris. L’attestation est délivrée par le préfet de région aux personnes qui ont suivi une formation conclue par un examen écrit obligatoire, sur un référentiel de connaissances défini par le ministre chargé des transports. Les centres de formation sont agréés par le préfet de région pour ${X.centre_agrement_max_ans} ans au plus, et contrôlés : l’agrément peut être suspendu ou retiré (articles R3113-39-1 à R3113-39-6). La personne qui gère une entreprise visée au 6° de l’article 5 du décret n° 85-891 du 16 août 1985 et qui demande l’attestation est dispensée de la formation.</p>
<p>C’est cette attestation que l’usage appelle encore « capacité LOTI », en souvenir de la loi d’orientation des transports intérieurs du 30 décembre 1982. Le nom est resté, le régime est aujourd’hui celui du code des transports.</p>

<h2>Le piège des services occasionnels en zone urbaine</h2>
<p>L’attestation limitée ouvre le transport de personnes avec des véhicules légers, mais le code des transports en encadre l’usage. Depuis le 1er janvier 2021, l’${h.src('ctL3112_1', 'article L3112-1')} impose que, lorsque le départ et l’arrivée d’un transport occasionnel se situent dans le ressort d’une même autorité organisatrice soumise à l’obligation d’établir un plan de mobilité, le service soit exécuté avec un véhicule comportant plus de ${X.places_passagers_max_m1} places assises en plus du conducteur. Les services occasionnels en véhicule léger sont en outre soumis aux règles de réservation préalable des taxis et VTC (article L3120-2).</p>
<p>En pratique, l’activité d’une entreprise de transport léger se concentre sur ce que ces règles laissent ouvert : trajets qui sortent du ressort de l’autorité organisatrice, transport scolaire ou conventionné avec une collectivité, services réguliers. Vérifiez votre modèle sur votre territoire avant d’investir dans la formation.</p>

<h2>Expérience, actualisation, attestations étrangères</h2>
<p>Une personne qui n’a pas géré d’entreprise de transport public de personnes pendant les ${X.cappro_actualisation_inactivite_ans} années précédant sa demande peut devoir suivre, avant d’être désignée gestionnaire de transport, une formation d’actualisation des connaissances dans un centre habilité (article R3113-41). Les attestations délivrées dans un autre État de l’Union européenne valent preuve suffisante (article R3113-37), et celles délivrées avant le ${h.date(X.attestations_equivalentes_avant)} sont réputées équivalentes au modèle européen (article R3113-42).</p>

<h2>Après l’attestation</h2>
<p>L’attestation n’est qu’une des quatre conditions de l’inscription au registre. L’entreprise doit aussi justifier d’un établissement, de l’honorabilité professionnelle de ses dirigeants et de sa capacité financière, puis reçoit une licence et autant de copies certifiées que de véhicules. Ces étapes, et les montants de capitaux à réunir, sont détaillés sur la page ${h.a('licence-transport', 'licence de transport')}. Le choix de la structure juridique, entreprise individuelle ou société, se pose ensuite comme pour tout transporteur : la page ${h.a('statut-vtc', 'statut juridique du chauffeur')} en résume les termes, et la page ${h.a('devenir-chauffeur-vtc', 'devenir chauffeur VTC')} décrit l’autre voie, celle du transport particulier.</p>
`,
  },
  en: {
    slug: 'passenger-transport-competence',
    nav: 'Passenger transport competence',
    card: 'The transport manager’s certificate: exam, diplomas, experience and what it allows.',
    title: 'Passenger Transport Competence France 2026: Exam and Routes',
    description: `Passenger transport competence in France, 2026: full certificate or one limited to ${X.leger_places_conducteur_inclus}-seat vehicles, written exam, diplomas or ${X.cappro_experience_leger_ans} years of managing a firm.`,
    h1: 'The passenger transport competence certificate in France',
    intro: 'No public passenger transport company joins the French register without a transport manager who holds this certificate.',
    resume: `In France, the capacité de transport de personnes is the certificate of professional competence that a company’s transport manager must hold before a public road passenger transport business can be entered on the State register (Transport Code, articles L3113-1 and R3113-38). The regional prefect issues it in two forms. The full certificate covers every vehicle, coaches and buses included, and is obtained through a written exam on the subjects in annex I of EU Regulation 1071/2009 (article R3113-35) or a diploma covering all of them. The limited certificate covers vehicles with no more than ${X.leger_places_conducteur_inclus} seats including the driver; it takes a course at an approved centre followed by a written exam (article R3113-39), or ${X.cappro_experience_leger_ans} years of continuous management of a passenger transport firm, provided that activity stopped less than ${X.cappro_interruption_max_ans} years ago (article R3113-40). Taxi and VTC (private hire) drivers do not need it: they fall under a separate part of the code and work with a professional driver card.`,
    faqs: [
      { q: 'Do I need a transport competence certificate to work as a VTC driver?', a: 'No. Article L3120-1 of the Transport Code puts paid journeys in vehicles with fewer than ten seats, taxis and VTCs, under a separate title that excludes public group transport. A VTC driver passes the chamber of trades (CMA) exam, gets a professional card and registers the business on the VTC register. The competence certificate is for group transport companies.' },
      { q: 'What do people in France mean by a “capacité LOTI”?', a: `It is the everyday name for the competence certificate limited to vehicles of ${X.leger_places_conducteur_inclus} seats or fewer, driver included. LOTI refers to the 1982 domestic transport framework act, whose rules now sit in the Transport Code. The regional prefect issues the certificate after a course and a written exam, on a listed diploma, or after ${X.cappro_experience_leger_ans} years managing a passenger transport firm (articles R3113-39 and R3113-40).` },
      { q: 'Is there a way to get the certificate without sitting the exam?', a: `Two. A diploma on the official list that covers every required subject qualifies you (articles R3113-36 and R3113-40). For the small-vehicle certificate, ${X.cappro_experience_leger_ans} years of continuous, main-activity management of a public passenger transport firm are enough, as long as you stopped less than ${X.cappro_interruption_max_ans} years ago. Experience counts for the full certificate only if it covered the ten years before 4 December 2009.` },
      { q: 'Does the competence certificate need renewing?', a: `Articles R3113-35 to R3113-42 give it no expiry date. However, if you have not managed a public passenger transport firm in the ${X.cappro_actualisation_inactivite_ans} years before applying, the regional prefect may require a knowledge refresher course at an approved centre before you are appointed transport manager (article R3113-41).` },
      { q: 'I hold a competence certificate from another EU country. Is it valid in France?', a: 'Yes. Article R3113-37 of the Transport Code accepts certificates issued by the competent authorities of other EU member states, on the model set by Regulation 1071/2009, as sufficient proof. Certificates issued before 4 December 2011 are treated as equivalent (article R3113-42). Certificates from outside the EU are not covered by these articles.' },
      { q: 'Can a small-vehicle operator run occasional trips within a city?', a: `Not everywhere. Under article L3112-1 of the Transport Code, when an occasional journey starts and ends within the area of a single transport authority that must adopt a mobility plan, it has to be run with a vehicle that has more than ${X.places_passagers_max_m1} seats besides the driver’s. Light vehicles are therefore ruled out there.` },
    ],
    body: (h) => `
<h2>What the certificate is for</h2>
<p>Every public passenger transport company established in France must be entered on a register kept by the State, and entry can depend on conditions of establishment, good repute, financial standing and professional competence (${h.src('ctL3113', 'article L3113-1 of the Transport Code')}). Competence is not assessed for the company as a whole: it is carried by one person, the transport manager, who must hold the certificate (article R3113-38). In a small firm that is usually the owner.</p>
<p>The certificate does not entitle anyone to drive; it is a management qualification. A coach driver needs a D licence and the initial driver qualification, covered in the ${h.a('devenir-chauffeur-bus', 'becoming a bus driver')} guide. One person can hold both roles.</p>

<h2>Who needs it and who does not</h2>
<p>The certificate concerns public group transport: scheduled routes, school transport, occasional services such as excursions, event shuttles and group transfers, and on-demand transport. The company sells passenger journeys for payment.</p>
<p>Two groups are outside it by the very structure of the code. Taxis and VTCs (voitures de transport avec chauffeur, the French private hire cars) have their own title, covering paid journeys in vehicles with fewer than ten seats and excluding public group transport (${h.src('ctL3120', 'article L3120-1')}): their key document is the professional card obtained after the chamber of trades exam, plus, for VTCs, the ${h.a('registre-vtc', 'VTC register')}. Private services are the second group: a company or association carrying its own staff or members for its normal needs is not doing public transport (${h.src('ctL3131', 'article L3131-1')}).</p>

<h2>Two certificates, two scopes</h2>
${h.table(['', 'Full certificate', `Limited to ${X.leger_places_conducteur_inclus} seats`], [
  ['Vehicles covered', 'all, including coaches and buses', `${X.leger_places_conducteur_inclus} seats or fewer, driver included`],
  ['Exam route', 'written exam on annex I of Regulation 1071/2009 (R3113-35)', 'course at an approved centre, then a written exam on a ministry syllabus (R3113-39)'],
  ['Diploma route', 'diploma covering all annex I subjects (R3113-36, 1°)', 'diploma covering the syllabus, sometimes plus the written exam (R3113-40, 1°)'],
  ['Experience route', `continuous management during the ${X.cappro_experience_lourd_ans} years before 4 December 2009 (R3113-36, 2°)`, `${X.cappro_experience_leger_ans} years of continuous, main-activity management, stopped less than ${X.cappro_interruption_max_ans} years ago (R3113-40, 2°)`],
], 'Source: Transport Code, articles R3113-35 to R3113-40, read on Légifrance on 4 October 2026')}
<p>Which one you need depends on the fleet, not on the size of the business. A firm running a single minibus with more than nine seats including the driver needs the full certificate; a firm with ten people carriers of eight passenger seats can manage with the limited one.</p>

<h2>The exam for the full certificate</h2>
<p>${h.src('ctR3113CapPro', 'Article R3113-35')} requires a compulsory written exam on the subjects listed in annex I of the 2009 EU regulation governing road haulage and passenger operators. The syllabus spans civil, commercial, employment and tax law, business and financial management, market access, technical standards and road safety. The exam is funded by a fee for the service, limited to a single sitting. The national jury brings together officials, trade bodies and training providers; its make-up is set by the ${h.src('arreteJuryCapacite', 'order of 2 September 2025')}.</p>
<p>The articles we read do not set the fee, the session dates or the pass mark: those are published separately by the authorities each year. We will not quote them until we have read them on a dated official source. The exam is in French, which is worth weighing if French is not your first language.</p>

<h2>The certificate for light vehicles</h2>
<p>Article R3113-39 covers firms that use only vehicles with ${X.leger_places_conducteur_inclus} seats or fewer, driver included. The regional prefect issues the certificate to people who have completed a course ending in a compulsory written exam, on a knowledge syllabus set by the transport minister. Training centres are approved by the regional prefect for up to ${X.centre_agrement_max_ans} years and inspected; approval can be suspended or withdrawn (articles R3113-39-1 to R3113-39-6). Someone managing a firm covered by point 6 of article 5 of decree no. 85-891 of 16 August 1985 who applies for the certificate is excused the course.</p>
<p>This is the certificate still called “capacité LOTI” in everyday French, after the domestic transport framework act of 30 December 1982. The nickname stuck; the rules are now those of the Transport Code.</p>

<h2>The catch with occasional trips in urban areas</h2>
<p>The limited certificate opens passenger transport with light vehicles, but the code restricts how they are used. Since 1 January 2021, ${h.src('ctL3112_1', 'article L3112-1')} has required that, where an occasional journey starts and ends in the area of a single transport authority obliged to draw up a mobility plan, it is run with a vehicle that has more than ${X.places_passagers_max_m1} seats besides the driver’s. Occasional services in light vehicles are also bound by the prior-booking rules that apply to taxis and VTCs (article L3120-2).</p>
<p>In practice, a light-vehicle operator builds its business on what those rules leave open: journeys leaving the authority’s area, school or contracted transport for a local authority, and scheduled services. Test your business model against your own area before paying for a course.</p>

<h2>Experience, refreshers and certificates from abroad</h2>
<p>Someone who has not managed a public passenger transport firm in the ${X.cappro_actualisation_inactivite_ans} years before applying may be required to take a knowledge refresher course at an approved centre before being appointed transport manager (article R3113-41). Certificates issued in another EU state count as sufficient proof (article R3113-37), and those issued before ${h.date(X.attestations_equivalentes_avant)} are treated as equivalent to the EU model (article R3113-42).</p>

<h2>After the certificate</h2>
<p>The certificate is only one of four conditions for entry on the register. The company must also show an establishment, the good repute of its managers and its financial standing, after which it receives a licence and one certified copy per vehicle. Those steps and the capital required are set out on the ${h.a('licence-transport', 'transport licence')} page. Choosing a legal structure, sole trader or company, comes next as for any operator: the ${h.a('statut-vtc', 'driver business structure')} page sums up the options, and the ${h.a('devenir-chauffeur-vtc', 'becoming a VTC driver')} guide covers the other route, private hire.</p>
`,
  },
});
